### ISSUE TITLE
MC8 Print Issue in 3.5.0

### ISSUE THREAD

**Issue by cmds4410** [Morningstar-Engineering/MC8-MIDI-Controller#1]
Whenever text is printed to my MC8's screen via the editor (either web or Mac desktop), it won't clear until I reset my device. My unit is on 3.5.0 and the issue is 100% reproducible. Toggling Edit Mode reproduces the issue as well. Should I downgrade to 3.4.3?

**Comment by tyzjames** [comment]
Hi! Thanks for the feedback.

Yes, that issue was present. Can you try the latest v3.5.0 update?

https://github.com/Morningstar-Engineering/MC8-MIDI-Controller/releases/tag/3.5.0

**Comment by cmds4410** [comment]
Hey James, that did the trick! Sorry for the confusion, I assumed my device was on the latest firmware. Thank you for responding so quickly!
