### ISSUE TITLE
Bank settings not loading on entering bank

### ISSUE THREAD

**Issue by Classic07** [Morningstar-Engineering/MC8-MIDI-Controller#11]
Bank settings set for on entry are not activating when entering the bank

**Comment by tyzjames** [comment]
Can you share a screenshot of your preset settings in the editor for this? Are you referring to the Bank Jump message or the Bank Preset On Enter messages?

**Comment by Classic07** [comment]
<img width="2048" alt="Screenshot 2021-08-20 at 17 36 10" src="https://user-images.githubusercontent.com/89267618/130265761-d4488426-87cb-4c33-9604-d4f6f2804b69.png">

The issue is exhibited on bank jump rather than specifically entry. The bank jump command seems to result in the 'on entry' commands being ignored.

**Comment by tyzjames** [comment]
check your Bank Jump messages - there are now additional settings there so you can select whether to execute bank presets on enter/exit when you bank jump. It might be turned off by default. We have not implemented a function to initialise all these values for this update yet

**Comment by Classic07** [comment]
That's it thanks tyuzjames. Which setting do I need to enact destination presets on entering the new bank?

**Comment by Classic07** [comment]
Don't worry - all sorted thank you!
