### ISSUE TITLE
Bank jump after backing up all banks

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#12]
Not a big problem in the scheme of things, however, if you are on bank01 when you call for an all banks backup it completes and leaves the MC8 on bank30 and I have two button combos disabled so have to go back in to the web interface to get back to bank01. It would be better to a) leave either where it was or b) default to bank01

**Comment by tyzjames** [comment]
Ah yes, we're aware of this. I'll handle this in the next update, thanks!

**Comment by tyzjames** [comment]
this is fixed in the 2021-09-02 v3.9 beta update.
