### ISSUE TITLE
Toggle Preset and Toggle Mode

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#14]
I am probably continuing to be foolish but the two things seem to be acting differently.

If I use the Toggle Mode with Release: Pos 1 turning on a pedal and Release: Pos 2 turning it off everything is fine. I can also use Engage Preset with Release to turn it on and off if that button exists in same Bank.

If I swap Toggle Mode for using Toggle Prest on Release the main button works but the Engage Prest only ever turns the pedal on, it does not seem to get to Pos 2.

In my mond these two should be equivalent and clearly the main button still works as planned BUT for some reason the remote button fails . . .

**Comment by psweetie** [comment]
As an example the backup file has a Bank 10 - Test
It has a Klon Preset on A and a Switch A Preset on D which is supposed to turn A on/off. This pair uses Toggle Preset and it doesn't work, or rather only ever turns the pedal on.
It has another Klon Preset on E and a Switch E Preset on F which is supposed to turn E on/off. This pair uses Toggle Mode and it does work. 
I have tried various combinations of global vs local variables and it seems to make no difference. I am using the Toggle Preset and need it to work as the Toggle Mode acts on Press and therefore is triggered by Long Press etc. This gets in the way of other functions on that button I want to use . . .
[Morningstar_MC8_All_Banks_Backup_File (19).txt](https://github.com/Morningstar-Engineering/MC8-MIDI-Controller/files/7100583/Morningstar_MC8_All_Banks_Backup_File.19.txt)

**Comment by tyzjames** [comment]
Yup that looks like unintended behaviour. Preset D should be able to toggle Preset A back to Pos 1 with the engage preset message type. Let me check it out..

**Comment by tyzjames** [comment]
Ok I have fixed it - will publish an update later today. Do let me know if the issue still isnt resolved.

**Comment by psweetie** [comment]
looks good James, will continue to test but today's update seems to have fixed it
