### ISSUE TITLE
Toggle Mode On and Long Press

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#17]
If you want to have both Long Press and a Press commands operate separately on the same Preset advice is to use Release rather than Press then the two do not interact. However, if you turn on Toggle Mode it is triggered by both the Release action and also by the Long Press action. Is this intended behaviour? In which case you have to turn off the Toggle Mode and use a Toggle Prest command to determine exactly when the toggle state changes.

**Comment by tyzjames** [comment]
Yes, if Toggle Mode is on, it will be triggered by any action.  If you want a specific action to toggle the preset, you should use the Toggle Preset action.

**Comment by psweetie** [comment]
Thanks James, that makes sense

Regards
Philip

***@***.******@***.***>
