### ISSUE TITLE
Release 3.9.0 29th Sept Bricks MC8

### ISSUE THREAD

**Issue by Classic07** [Morningstar-Engineering/MC8-MIDI-Controller#18]
The latest release causes the MC8 to brick and become unresponsive to button press and does not reboot. Once powered off and back it only shows blocks on screen. However, the device _is_ responsive behind the scenes and can accept the previous release version from 10th September and the device reboots and works correctly again.

My PCB is the blue version and hasn't been updated to the latest/updated version yet.

**Comment by tyzjames** [comment]
Thanks for the report. Nothing major has been changed besides adding some new features with regards to message types, so it is unlikely that that will happen. I'll test the upload on another MC8, but in the meantime, can you confirm that you uploaded the correct firmware meant for the MC8 (not MC6 or MC3)?

**Comment by Classic07** [comment]
Discovered what's causing it and you are correct, the firmware is for the MC6 however that's the firmware download available on the **MC8** page. Note the URL and text at the top of the page:

<img width="2048" alt="Screenshot 2021-09-29 at 15 58 24" src="https://user-images.githubusercontent.com/89267618/135295238-6308129c-00eb-42b8-a526-5d16e5b9b228.png">

<img width="2048" alt="Screenshot 2021-09-29 at 15 58 33" src="https://user-images.githubusercontent.com/89267618/135295250-a7c4a5e4-cb7d-4353-901f-52a6eeca425a.png">

**Comment by tyzjames** [comment]
my bad! I uploaded the wrong files. I have fixed it - do check and let me know if you continue to face any issues.

**Comment by Classic07** [comment]
The latest MC8 files are now available and it's working as expected now, thank you. 

<img width="2048" alt="Screenshot 2021-09-29 at 16 05 12" src="https://user-images.githubusercontent.com/89267618/135296445-169348ea-49b1-4267-94b6-420581aab2a0.png">
!
