### ISSUE TITLE
Activity Monitor

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#19]
Really liking the ability to see what is actually being triggered. Useful to debug your messages. Would be very useful to see the state of the toggle / toggle group (incl shift) as part of the readout . . .

**Comment by tyzjames** [comment]
ah yes, toggle position would definitely be useful. Will look into adding that, thanks!

**Comment by tyzjames** [comment]
done

**Comment by psweetie** [comment]
Looking good, what does it mean when it shows Position: Both, I thought it was a binary option of Pos 1 or Pos 2?

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
That is great

Regards
Philip

***@***.******@***.***>
