### ISSUE TITLE
Tap Tempo Inaccurate

### ISSUE THREAD

**Issue by cmds4410** [Morningstar-Engineering/MC8-MIDI-Controller#2]
The tap tempo functionality of the MIDI clock on my MC8 is consistently around 20 to 25 bpm below what it should be. I verified against 2 different sources (Ableton and a metronome app on my phone). The bpm _does_ seem to be producing reliably consistent results with repeated input, but it's just always much lower than it should be. I have only tested on firmware 3.5.1, but I can try downgrading and testing on an older firmware if that would be helpful. By the way, loving all the new updates, especially the MIDI dictionary and bank reordering!

**Comment by tyzjames** [comment]
this has been fixed in firmware v3.8
