### ISSUE TITLE
Storm of SysEx messages

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#22]
In the latest release, when I issue a MIDI Clock Tap message I get a storm of SysEx messages tyhat just keep on going. Have tried with MIDI persist on and off and makes no difference.

**Comment by psweetie** [comment]
backup file
storm created when in Bank1 and using Tap functionality on Preset E

[Morningstar_MC8_Backup_File_20211029.txt](https://github.com/Morningstar-Engineering/MC8-MIDI-Controller/files/7444137/Morningstar_MC8_Backup_File_20211029.txt)
 
Philip

**Comment by tyzjames** [comment]
The SysEx messages is actually incoming MIDI clock messages - I think I accidentally removed the filter. I have added it (the filter) back in the editor - not related to the MC8 firmware.

**Comment by psweetie** [comment]
Aha, thanks James, certainly Janet seen them before andi an returning incoming MIDI clock in system settings

Philip
***@***.***
+44 (7540) 664785
________________________________
