### ISSUE TITLE
Using a switch in one bank to remote preset in another bank broken 

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#25]
I have a "stomp" bank which basically calls "engage preset" with release set for presets in other baks. Thgis prevents me having to replicate complicated MIDI command stacks. Working finr in 3.9.6 but broken in 3.9.7 when loaded this morning. Back to 3.9.6 and all works again . . .

Philip

**Comment by tyzjames** [comment]
Thanks for reporting this. Yes I was experiencing intermittent behaviour when using engage preset. I have fixed the issue in today's release. If you do manage to give it a go, let me know if the issue is resolved for you

**Comment by psweetie** [comment]
Thanks James, will try this later today

Philip
***@***.***
+44 (7540) 664785
________________________________

**Comment by psweetie** [comment]
Hi James
Will test more thoroughly tomorrow, but looks like remote operations are working again.

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
version 0108 fixes the problem for me
