### ISSUE TITLE
Engage Preset seems to have no action within same Bank

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#26]
If I use Engage Preset from within the same Bank there seems to be no action at all, jist ignores it. If I use the individual PC/CC commands everything works but issuing an Engage Preset with Release action does not trigger those actions. Works fine across Banks.

**Comment by tyzjames** [comment]
Thanks! this is a known issue and we have fixed it - waiting to release in next minor update. looking through a few more bug first.  Attaching the latest build here
[Uploading 2022-02-08_MC8_Firmware_v_3_9_7.hex.zip…]()
.

**Comment by psweetie** [comment]
Thanks James, that link doesn’t seem to work?

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
Got it, had to be within GitHub

Regards
Philip

***@***.******@***.***>

From: Philip Sweetman ***@***.***>
Sent: 09 February 2022 09:40
To: Morningstar-Engineering/MC8-MIDI-Controller ***@***.***>
Cc: Philip Sweetman ***@***.***>
Subject: RE: [Morningstar-Engineering/MC8-MIDI-Controller] Engage Preset seems to have no action within same Bank (Issue #26)

Thanks James, that link doesn’t seem to work?

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
that works, thanks James
