### ISSUE TITLE
Saving bank messages problem

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#4]
In the 3.9.0 beta I was saving set expression messages in various banks such that the expression pedal worked for that pedal when the bank was entered. The message ended up being replicated across multiple banks and the names of the two banks got corrupted. When I went back to the release version the messages saved fine and no problem with the Bank names.

**Comment by tyzjames** [comment]
thanks for the feedback. was this on the latest firmware? In one of the first few releases there was an issue with the save function from the editor that might have caused what you encountered. Do you have the filename of the firmware you used?

**Comment by psweetie** [comment]
Hi James

File name is 2021-05-19_v2_MC8_Firmware_v3_9_0_Beta.hex

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
Hi James

Just downloaded latest version and it doesn’t appear to do the same thing, it appears to act correctly. Will continue to use and report if it errors

Regards
Philip

***@***.******@***.***>

From: Philip Sweetman ***@***.***>
Sent: 27 May 2021 09:15
To: Morningstar-Engineering/MC8-MIDI-Controller ***@***.***>
Cc: Philip Sweetman ***@***.***>
Subject: RE: [Morningstar-Engineering/MC8-MIDI-Controller] Saving bank messages problem (#4)

Hi James

File name is 2021-05-19_v2_MC8_Firmware_v3_9_0_Beta.hex

Regards
Philip
***@***.******@***.***>

**Comment by tyzjames** [comment]
Thanks for the feedback! Ok do let me know if you face the same issue again.
