### ISSUE TITLE
Toggle Mode

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#6]
Current Toggle Mode I believe is activated on a button Press action. Thus it is activated when the user Long Presses or Double Taps which gets in the way of separating those functions. You have to disable Toggle Mode and add a Toggle Preset command on Release to get that more separated functionality. Would it be better to have it run by default off a Release?

**Comment by tyzjames** [comment]
Yes, the steps you specified are correct if you just want to toggle the preset with Release action. 
You'll need to add that toggle preset message with the selected action. We can't change it to be release by default because that will break the workflows for other users

**Comment by psweetie** [comment]
Thanks James, understood

Regards
Philip

***@***.******@***.***>
