### ISSUE TITLE
problem with global toggle groups when using toggle preset

### ISSUE THREAD

**Issue by psweetie** [Morningstar-Engineering/MC8-MIDI-Controller#8]
These are a great idea and have used them in a number of places. If I create a preset which engages / disengages a prest on a pedal it work fine. If I use a button in another bank to just engage that preset both presets blink and all is well. 

In one case I have a double tap set to return to home page and the release action also uses toggle preset to avoid the double tap changing the preset state. When this uses the global toggle group and the preset is called from another button in another bank the MC8 freezes. Do it without the set toggle all is well.

**Comment by tyzjames** [comment]
Thanks for raising this. Can you share with me your controller data file so I can test it and see what might be the issue?

**Comment by psweetie** [comment]
Is that the preset backup file James?

Regards
Philip

***@***.******@***.***>

**Comment by tyzjames** [comment]
It's the "All Banks" function in the Controller Backup tab.

**Comment by psweetie** [comment]
This shows bank 1 preset P selecting bank 4 preset b. Note that this works. If it is set to toggle bank 4 preset a, that is where it freezes as that prest uses the manual sett toggle method . . .

Regards
Philip

***@***.******@***.***>

**Comment by psweetie** [comment]
Tried calling Engage Preset with new staging and still the same behaviour. I have a Klon Preset in the Stomp Bank. It calls the Klon Preset in the Drive Bank. If I replicate the code in the Stomp Bank it all works, if I use the Engage Preset with Release action it turns the pedal on correctly BUT th MC8 freezes and has to be rebooted. The backup is attached.
[Morningstar_MC8_All_Banks_Backup_File (17).txt](https://github.com/Morningstar-Engineering/MC8-MIDI-Controller/files/7098014/Morningstar_MC8_All_Banks_Backup_File.17.txt). Just renamed from .json so it uploads

**Comment by tyzjames** [comment]
@psweetie thanks for the file. I have loaded it into my controller and replicated the issue. Will look into it now.

**Comment by tyzjames** [comment]
@psweetie can you try the file uploaded today and see if it solves your issue? I have fixed the issue that causes the MC8 to freeze

**Comment by psweetie** [comment]
no freezes any more
